config/routes.rb
Rails.application.routes.draw do
  resources :outings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "outings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/outing.rb
class Outing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/outings_controller.rb
class OutingsController < ApplicationController
  before_action :set_outing, only: %i[ show edit update destroy ]

  # GET /outings or /outings.json
  def index
    @outings = Outing.all
  end

  # GET /outings/1 or /outings/1.json
  def show
  end

  # GET /outings/new
  def new
    @outing = Outing.new
  end

  # GET /outings/1/edit
  def edit
  end

  # POST /outings or /outings.json
  def create
    @outing = Outing.new(outing_params)

    respond_to do |format|
      if @outing.save
        format.html { redirect_to @outing, notice: "Outing was successfully created." }
        format.json { render :show, status: :created, location: @outing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @outing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outings/1 or /outings/1.json
  def update
    respond_to do |format|
      if @outing.update(outing_params)
        format.html { redirect_to @outing, notice: "Outing was successfully updated." }
        format.json { render :show, status: :ok, location: @outing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @outing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outings/1 or /outings/1.json
  def destroy
    @outing.destroy!

    respond_to do |format|
      format.html { redirect_to outings_path, status: :see_other, notice: "Outing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outing
      @outing = Outing.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def outing_params
      params.expect(outing: [ :location, :date ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content: "text/html; charset=UTF-8" http-equiv="Content-Type" /
    title= content_for(:title) || "Bill Buddy"
    meta content: "width=device-width,initial-scale=1", name: "viewport" /
    meta content: "yes", name: "apple-mobile-web-app-capable" /
    meta content: "yes", name: "mobile-web-app-capable" /
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    link href: "/icon.png", rel: "icon", type: "image/png" /
    link href: "/icon.svg", rel: "icon", type: "image/svg+xml" /
    link href: "/icon.png", rel: "apple-touch-icon" /
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
  body
    = yield

app/views/outings/_form.html.erb
<%= form_with(model: outing) do |form| %>
  <% if outing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(outing.errors.count, "error") %> prohibited this outing from being saved:</h2>

      <ul>
        <% outing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/outings/_outing.html.erb
<div id="<%= dom_id outing %>">
  <p>
    <strong>Location:</strong>
    <%= outing.location %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= outing.date %>
  </p>

</div>

app/views/outings/edit.html.erb
<% content_for :title, "Editing outing" %>

<h1>Editing outing</h1>

<%= render "form", outing: @outing %>

<br>

<div>
  <%= link_to "Show this outing", @outing %> |
  <%= link_to "Back to outings", outings_path %>
</div>

app/views/outings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Outings" %>

<h1>Outings</h1>

<div id="outings">
  <% @outings.each do |outing| %>
    <%= render outing %>
    <p>
      <%= link_to "Show this outing", outing %>
    </p>
  <% end %>
</div>

<%= link_to "New outing", new_outing_path %>

app/views/outings/new.html.erb
<% content_for :title, "New outing" %>

<h1>New outing</h1>

<%= render "form", outing: @outing %>

<br>

<div>
  <%= link_to "Back to outings", outings_path %>
</div>

app/views/outings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @outing %>

<div>
  <%= link_to "Edit this outing", edit_outing_path(@outing) %> |
  <%= link_to "Back to outings", outings_path %>

  <%= button_to "Destroy this outing", @outing, method: :delete %>
</div>